#-----------------------------------------------------------------------------
# Name:        Exercise 4 (Exercise4.py)
# Purpose:     Using inputs, concatenation, and converting to strings
#
# Author:      vonlugersbutter
# Created:     Friday, October 12, 2018
# Updated:     Monday, October 15, 2018
#-----------------------------------------------------------------------------

name = input("Forgive me, hero. My oblivion has made me forget your name. What is your name?")
print("You have awoken, " + name + ". Hyrule awaits.")
print()

print("You are in Ordon village, wielding the Ordon Sword.")
print("Oh no! You were robbed!! All your money is gone!!")
print("Erica: " + name + ", what's wrong. Huh? What do you mean you were robbed?! That's horrible! I'll tell you what, if you had any debt on me, I clear it all away!!")
print("Erica: No need to thank me. I'm here to help, " + name + "!")
print()

rupees = int(0)

print("You now have 0 rupees.")
print("You need to find some way to get more rupees. Try looking for some way to get some.")
print()
print("a. Beg Jackie for money.")
print("b. Beg Erica for money.")
print("c. Break that pot over there. It belongs to Ayesha, and she won't give you money the easy way.")
print("d. Cut some grass. You could become a part-time lawnmower.")
get_rupees = input("Which of the above would you like to do?")
print()
if get_rupees == "a":
  print("Jackie: Hmm? You need rupees. Gah, here you go, " + name + ". I suppose a hero needs all the help they can get.")
  rupees = rupees + 20
  print()
  print("Jackie gave you 20 rupees. You now have " + str(rupees) + " rupees.")

elif get_rupees == "b":
  print("Erica: Huh? Well, I'm sorry, " + name + ", but I can't give you any. You'll have to find some rupees yourself.")
  print("You now have " + str(rupees) + " rupees.")

elif get_rupees == "c":
  print("Heh, heh. Good choice, " + name + ". Ayesha was never nice to you anyway.")
  print("The pot broke open. How nice.")
  rupees = rupees + 20
  print("You now have " + str(rupees) + " rupees.")

elif get_rupees == "d":
  print("Well, I suppose all heroes have to do some honest hard work.")
  print("You swung the Ordon Sword.")
  print("Sweet. Grass has money in it.")
  rupees = rupees + 10
  print("You now have " + str(rupees) + " rupees.")

print()
print("Jackie: " + name + "!! I have a quest for you!! The Gorons of Death Mountain are terrified!")
print("Jackie: Mr. Seidel, their leader, has disappeared into the mountain, and threatens to fight anyone that goes in after him!")
print("Jackie: " + name + ", You're the only one that can save the Gorons from Mr. Seidel's wrath, but you'll need a Hylian Shield to face him.")
print()
print("Erica came outside to join you and Jackie.")
print()
print("Erica: Are you talking about the Hylian Shield? I can give you one for just 300 rupees!")
print("Jackie: That's perfect! " + name + ", you're going to have to find that many rupees!!")
print()
print("You have at least started getting some rupees, which is a good start. Maybe you could go play Jasmine's game.")
print()

print("a. Play Jasmine's game.")
play_game = input("What would you like to do?")

if play_game == "a":
  print("You are now inside of Jasmine's Game Emporium.")
  print("Jasmine: Welcome! Welcome! How are you today, " + name + "?")
  print()
  print("a. I'm fine, thank you.")
  print("b. Eh? Why do you care?!")
  being_nice = input("What do you want to say to Jasmine?")
  print()
  if being_nice == "a":
    print("Jasmine: It is good to see you, " + name + "! Well, then would you like a chance to win 300 rupees?")
    print("Jasmine: Ah, I knew you would! Well step right up and play Jasmine's Game!!")
    print()
    print("Jasmine: Now the game is, you have to guess the number, which is from 1 to 50, I am thinking of in 3 tries!")
    secret_number = int(47)
    print("Jasmine: Alright, I have decided on my secret number! Try guessing now!")
    print()
    
    guess_1 = int(input("What do you think the secret number is?"))
    print()
    if guess_1 == secret_number:
      print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
      print("Jasmine: I can hardly believe it!")
      print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
      rupees = rupees + 300
      print()
      print("You now have " + str(rupees) + " rupees.")
      print()
      print("You are now outside.")
      print("Jackie: Wow! You won Jasmine's game! I knew you would!")
      print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
      print()
      print("You gave Erica " + str(rupees) + " rupees.")
      print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
      print("Erica gave you " + str(rupees-300) + ".")
      print()
      print("You now have the Hylian Shield.")
      print()
      print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
      print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
      
    elif (guess_1 > secret_number) and (guess_1 <= 50): 
      print("Jasmine: Nope! That's not the number I'm thinking of! My number is lower than that!")
      print("Jasmine: Why don't you try again, " + name + ".")
      print()
      guess_2 = int(input("What do you think the secret number is?"))
      print()
      if guess_2 == secret_number:
        print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
        print("Jasmine: I can hardly believe it!")
        print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
        rupees = rupees + 300
        print()
        print("You now have " + str(rupees) + " rupees.")
        print()
        print("You are now outside.")
        print("Jackie: Wow! You won Jasmine's game! I knew you would!")
        print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
        print()
        print("You gave Erica " + str(rupees) + " rupees.")
        print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
        print("Erica gave you " + str(rupees-300) + ".")
        print()
        print("You now have the Hylian Shield.")
        print()
        print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
        print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
      elif (guess_2 > secret_number) and (guess_2 <= 50): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is lower than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      elif (guess_2 < secret_number) and (guess_2 >= 1): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is higher than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      else:
        print("Jasmine: Hmm? Well if you're not going to play by the rules, then I don't wish to play the game with you!!")
        print("You are now outside.")
        print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
        print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
        print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
        print()
        print("GAME OVER")
          
    elif (guess_1 < secret_number) and (guess_1 >= 1): 
      print("Jasmine: Nope! That's not the number I'm thinking of! My number is higher than that!")
      print("Jasmine: Why don't you try again, " + name + ".")
      print()
      guess_2 = int(input("What do you think the secret number is?"))
      print()
      if guess_2 == secret_number:
        print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
        print("Jasmine: I can hardly believe it!")
        print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
        rupees = rupees + 300
        print()
        print("You now have " + str(rupees) + " rupees.")
        print()
        print("You are now outside.")
        print("Jackie: Wow! You won Jasmine's game! I knew you would!")
        print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
        print()
        print("You gave Erica " + str(rupees) + " rupees.")
        print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
        print("Erica gave you " + str(rupees-300) + ".")
        print()
        print("You now have the Hylian Shield.")
        print()
        print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
        print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
      elif (guess_2 > secret_number) and (guess_2 <= 50): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is lower than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      elif (guess_2 < secret_number) and (guess_2 >= 1): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is higher than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      else:
        print("Jasmine: Hmm? Well if you're not going to play by the rules, then I don't wish to play the game with you!!")
        print("You are now outside.")
        print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
        print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
        print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
        print()
        print("GAME OVER")
      
    else: #guess 1 else
      print("Jasmine: Hmm? Well if you're not going to play by the rules, then I don't wish to play the game with you!!")
      print("You are now outside.")
      print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
      print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
      print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
      print()
      print("GAME OVER")

  if being_nice == "b":
    print("Jasmine: Why, how rude of you! Hmph! Well, if you're here to play my Game, I certainly hope you don't win!!")
    print("Jasmine: Now the game is, you have to guess the number, which is from 1 to 50, I am thinking of in 3 tries!")
    secret_number = int(47)
    print("Jasmine: Alright, I have decided on my secret number! Try guessing now!")
    print()
    
    guess_1 = int(input("What do you think the secret number is?"))
    print()
    if guess_1 == secret_number:
      print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
      print("Jasmine: I can hardly believe it!")
      print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
      rupees = rupees + 300
      print()
      print("You now have " + str(rupees) + " rupees.")
      print()
      print("You are now outside.")
      print("Jackie: Wow! You won Jasmine's game! I knew you would!")
      print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
      print()
      print("You gave Erica " + str(rupees) + " rupees.")
      print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
      print("Erica gave you " + str(rupees-300) + ".")
      print()
      print("You now have the Hylian Shield.")
      print()
      print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
      print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
      
    elif (guess_1 > secret_number) and (guess_1 <= 50): 
      print("Jasmine: Nope! That's not the number I'm thinking of! My number is lower than that!")
      print("Jasmine: Why don't you try again, " + name + ".")
      print()
      guess_2 = int(input("What do you think the secret number is?"))
      print()
      if guess_2 == secret_number:
        print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
        print("Jasmine: I can hardly believe it!")
        print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
        rupees = rupees + 300
        print()
        print("You now have " + str(rupees) + " rupees.")
        print()
        print("You are now outside.")
        print("Jackie: Wow! You won Jasmine's game! I knew you would!")
        print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
        print()
        print("You gave Erica " + str(rupees) + " rupees.")
        print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
        print("Erica gave you " + str(rupees-300) + ".")
        print()
        print("You now have the Hylian Shield.")
        print()
        print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
        print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
      elif (guess_2 > secret_number) and (guess_2 <= 50): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is lower than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      elif (guess_2 < secret_number) and (guess_2 >= 1): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is higher than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
          
    elif (guess_1 < secret_number) and (guess_1 >= 1): 
      print("Jasmine: Nope! That's not the number I'm thinking of! My number is higher than that!")
      print("Jasmine: Why don't you try again, " + name + ".")
      print()
      guess_2 = int(input("What do you think the secret number is?"))
      print()
      if guess_2 == secret_number:
        print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
        print("Jasmine: I can hardly believe it!")
        print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
        rupees = rupees + 300
        print()
        print("You now have " + str(rupees) + " rupees.")
        print()
        print("You are now outside.")
        print("Jackie: Wow! You won Jasmine's game! I knew you would!")
        print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
        print()
        print("You gave Erica " + str(rupees) + " rupees.")
        print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
        print("Erica gave you " + str(rupees-300) + ".")
        print()
        print("You now have the Hylian Shield.")
        print()
        print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
        print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
      elif (guess_2 > secret_number) and (guess_2 <= 50): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is lower than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      elif (guess_2 < secret_number) and (guess_2 >= 1): 
        print("Jasmine: Nope! That's not the number I'm thinking of! My number is higher than that!")
        print("Jasmine: Why don't you try again, " + name + ".")
        print()
        guess_3 = int(input("What do you think the secret number is?"))
        print()
        if guess_3 == secret_number:
          print("Jasmine: What?!?! How did you do that?! You got it right! The secret number was " + str(secret_number) + "!!")
          print("Jasmine: I can hardly believe it!")
          print("Jasmine: Well, you win the game! Here's the 300 rupees!!")
          rupees = rupees + 300
          print()
          print("You now have " + str(rupees) + " rupees.")
          print()
          print("You are now outside.")
          print("Jackie: Wow! You won Jasmine's game! I knew you would!")
          print("Erica: Yay! Now then, the Hylian Shield is worth 300 rupees.")
          print()
          print("You gave Erica " + str(rupees) + " rupees.")
          print("Let's see. That means I need to give you " + str(rupees-300) + " rupees back.")
          print("Erica gave you " + str(rupees-300) + ".")
          print()
          print("You now have the Hylian Shield.")
          print()
          print("Jackie: Now you can face Mr. Seidel!! Go on, " + name + "! I know you'll be able to defeat him!")
          print("Your adventure will continue in another exercise. Farewell, for now, " + name + ".")
        elif guess_3 != secret_number:
          print("Jasmine: Well now, I'm sorry, " + name + ", but that's your third try. You didn't get my number right.")
          print("Jasmine: I'm quite sorry. But do play the game again if you wish later!")
          print()
          print("You are now outside.")
          print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
          print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
          print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
          print()
          print("GAME OVER")
      
    else: 
      print("Jasmine: Hmm? Well if you're not going to play by the rules, then I don't wish to play the game with you!!")
      print("You are now outside.")
      print("Jackie: What happened, " + name + "? Did you not win Jasmine's game?")
      print("Erica: Oh dear, I guess that means you can't buy the Hylian Shield.")
      print("Jackie: Don't worry, " + name + "! I'm sure you'll be able to get enough rupees to get the Hylian Shield!!")
      print()
      print("GAME OVER")
